---
- name: Install and Configure MySQL
  hosts: host2
  become: true
  become_user: root
  gather_facts: true
  tasks:
      - name: install mysql
        package:
            name: "{{item}}"
            state: present
            update_cache: yes
        loop:
          - libmysqlclient-dev
          - mysql-server
          - mysql-client
          - python-mysqldb

      - name: start and enable mysql
        service:
         name: mysql
         state: started
         enabled: yes
      - name: creatingmysql  user
        mysql_user:
         name: "{{dbuser}}"
         password: "{{dbpass}}"
         priv: '*.*:ALL'
         host: '%'
         state: present
      - name: creating db
        mysql_db:
         name: "{{dbname}}"
         state: present
      - name: "enable remote login"
        lineinfile:
         path: /etc/mysql/mysql.conf.d/mysqld.cnf
         regexp: '^bind-address'
         line: 'bind-address = 0.0.0.0'
      - name: "Restart Mysql" 
        service:
         name: mysql
         state: restarted 
      - name: "Create a Table "
        command: mysql -u shazil -pshazil -e "CREATE TABLE IF NOT EXISTS users (id int(11) NOT NULL AUTO_INCREMENT,username VARCHAR(50) NOT NULL, email VARCHAR(50) NOT NULL,password varchar(50) NOT NULL,trn_date datetime NOT NULL,PRIMARY KEY (id));" shazil
