---
- name: install apache & php & mysql
  hosts: host1
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: "Update apt-get repo and cache"
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: "Install appache2"
      package: name=apache2 state=present
    - name: "install appache2-php5"
      package: name=libapache2-mod-php state=present
    - name: "install php-cli"
      package: name=php-cli state=present
    - name: "install php-gd"
      package: name=php-gd state=present
    - name: "install php-mysql"
      package: name=php-mysql state=present
    - name: "install mysqlserver"
      package: name=mysql-server state=present

    - name: "copy file"
      copy: src=/home/ubuntu/ansible_project/files/
            dest=/var/www/html/example

    - name: "copy dbvar file"
      copy: src=/home/ubuntu/ansible_project/group_vars
            dest=/var/www/html/example

    - name: "copy file"
      copy: src=/home/ubuntu/ansible_project/conf.j2
            dest=/etc/apache2/sites-available/000-default.conf
    - name: Reload Apache
      service:
          name: apache2
          state: reloaded
    - name: Restart Apache
      service:
          name: apache2
          state: restarted

